
-- Ensure stores exist
INSERT INTO public.stores (id, name, website_url) VALUES
  ('aldi', 'Aldi', 'https://www.aldi.be'),
  ('albert_heijn', 'Albert Heijn', 'https://www.ah.nl'),
  ('carrefour', 'Carrefour', 'https://www.carrefour.be'),
  ('colruyt', 'Colruyt', 'https://www.colruyt.be'),
  ('jumbo', 'Jumbo', 'https://www.jumbo.com'),
  ('lidl', 'Lidl', 'https://www.lidl.be')
ON CONFLICT (id) DO NOTHING;

-- Create temp table for product definitions
CREATE TEMP TABLE temp_products (
  name text, category text, unit text, image text, base_price numeric
);

INSERT INTO temp_products VALUES
('Organic Bananas','Fruits & Vegetables','per kg','🍌',1.49),
('Fresh Strawberries','Fruits & Vegetables','per 500g','🍓',2.99),
('Avocados','Fruits & Vegetables','each','🥑',0.89),
('Red Apples','Fruits & Vegetables','per kg','🍎',1.99),
('Green Apples','Fruits & Vegetables','per kg','🍏',2.09),
('Oranges','Fruits & Vegetables','per kg','🍊',1.79),
('Lemons','Fruits & Vegetables','per 500g','🍋',1.49),
('Grapes Red','Fruits & Vegetables','per 500g','🍇',2.49),
('Grapes White','Fruits & Vegetables','per 500g','🍇',2.39),
('Watermelon','Fruits & Vegetables','each','🍉',3.99),
('Cantaloupe Melon','Fruits & Vegetables','each','🍈',2.99),
('Pineapple','Fruits & Vegetables','each','🍍',2.49),
('Mangoes','Fruits & Vegetables','each','🥭',1.89),
('Peaches','Fruits & Vegetables','per kg','🍑',3.49),
('Pears','Fruits & Vegetables','per kg','🍐',2.29),
('Cherries','Fruits & Vegetables','per 500g','🍒',4.99),
('Blueberries','Fruits & Vegetables','per 150g','🫐',2.99),
('Raspberries','Fruits & Vegetables','per 125g','🫐',3.49),
('Blackberries','Fruits & Vegetables','per 150g','🫐',3.29),
('Kiwi Fruit','Fruits & Vegetables','per 4 pack','🥝',1.99),
('Pomegranate','Fruits & Vegetables','each','🫐',1.79),
('Passion Fruit','Fruits & Vegetables','per 3 pack','🫐',2.49),
('Coconut','Fruits & Vegetables','each','🥥',1.99),
('Plums','Fruits & Vegetables','per 500g','🫐',2.69),
('Nectarines','Fruits & Vegetables','per kg','🍑',3.29),
('Clementines','Fruits & Vegetables','per kg','🍊',2.49),
('Limes','Fruits & Vegetables','per 4 pack','🍋',1.29),
('Grapefruit','Fruits & Vegetables','each','🍊',0.89),
('Dried Apricots','Fruits & Vegetables','per 200g','🫐',2.49),
('Dried Cranberries','Fruits & Vegetables','per 200g','🫐',2.79),
('Raisins','Fruits & Vegetables','per 500g','🫐',1.99),
('Dates Medjool','Fruits & Vegetables','per 250g','🫐',4.49),
('Carrots','Fruits & Vegetables','per kg','🥕',0.99),
('Tomatoes','Fruits & Vegetables','per kg','🍅',1.99),
('Cherry Tomatoes','Fruits & Vegetables','per 250g','🍅',1.49),
('Cucumbers','Fruits & Vegetables','each','🥒',0.79),
('Bell Pepper Red','Fruits & Vegetables','each','🫑',0.99),
('Bell Pepper Yellow','Fruits & Vegetables','each','🫑',1.09),
('Bell Pepper Green','Fruits & Vegetables','each','🫑',0.89),
('Broccoli','Fruits & Vegetables','each','🥦',1.49),
('Cauliflower','Fruits & Vegetables','each','🥦',1.79),
('Spinach Fresh','Fruits & Vegetables','per 200g','🥬',1.49),
('Lettuce Iceberg','Fruits & Vegetables','each','🥬',0.99),
('Romaine Lettuce','Fruits & Vegetables','each','🥬',1.19),
('Mixed Salad Bag','Fruits & Vegetables','per 150g','🥗',1.79),
('Onions','Fruits & Vegetables','per kg','🧅',0.89),
('Red Onions','Fruits & Vegetables','per kg','🧅',1.19),
('Garlic','Fruits & Vegetables','per 3 bulbs','🧄',0.99),
('Potatoes','Fruits & Vegetables','per 2.5kg','🥔',1.99),
('Sweet Potatoes','Fruits & Vegetables','per kg','🍠',1.79),
('Mushrooms White','Fruits & Vegetables','per 250g','🍄',1.29),
('Mushrooms Chestnut','Fruits & Vegetables','per 250g','🍄',1.49),
('Zucchini','Fruits & Vegetables','each','🥒',0.89),
('Eggplant','Fruits & Vegetables','each','🍆',1.29),
('Corn on the Cob','Fruits & Vegetables','per 2 pack','🌽',1.49),
('Green Beans','Fruits & Vegetables','per 400g','🫛',1.99),
('Asparagus','Fruits & Vegetables','per 500g','🫛',3.49),
('Celery','Fruits & Vegetables','each','🫛',1.29),
('Leek','Fruits & Vegetables','each','🫛',0.99),
('Cabbage White','Fruits & Vegetables','each','🥬',0.99),
('Red Cabbage','Fruits & Vegetables','each','🥬',1.09),
('Brussels Sprouts','Fruits & Vegetables','per 500g','🥬',1.79),
('Beetroot','Fruits & Vegetables','per 500g','🫛',1.29),
('Parsnips','Fruits & Vegetables','per 500g','🫛',1.49),
('Turnips','Fruits & Vegetables','per 500g','🫛',1.19),
('Radishes','Fruits & Vegetables','per bunch','🫛',0.89),
('Spring Onions','Fruits & Vegetables','per bunch','🧅',0.69),
('Fresh Herbs Mix','Fruits & Vegetables','per pot','🌿',1.49),
('Fresh Basil','Fruits & Vegetables','per pot','🌿',1.29),
('Fresh Parsley','Fruits & Vegetables','per bunch','🌿',0.79),
('Fresh Coriander','Fruits & Vegetables','per bunch','🌿',0.89),
('Fresh Mint','Fruits & Vegetables','per pot','🌿',1.29),
('Fresh Chives','Fruits & Vegetables','per pot','🌿',1.19),
('Ginger Root','Fruits & Vegetables','per 100g','🫛',0.99),
('Chili Peppers','Fruits & Vegetables','per 100g','🌶️',1.49),
('Whole Milk 1L','Dairy & Eggs','per liter','🥛',0.99),
('Semi-Skimmed Milk 1L','Dairy & Eggs','per liter','🥛',0.95),
('Skimmed Milk 1L','Dairy & Eggs','per liter','🥛',0.89),
('Whole Milk 2L','Dairy & Eggs','per 2L','🥛',1.79),
('Oat Milk 1L','Dairy & Eggs','per liter','🥛',1.89),
('Soy Milk 1L','Dairy & Eggs','per liter','🥛',1.69),
('Almond Milk 1L','Dairy & Eggs','per liter','🥛',1.99),
('Coconut Milk 1L','Dairy & Eggs','per liter','🥛',1.79),
('Free Range Eggs 10','Dairy & Eggs','per 10','🥚',2.49),
('Free Range Eggs 6','Dairy & Eggs','per 6','🥚',1.79),
('Organic Eggs 6','Dairy & Eggs','per 6','🥚',2.29),
('Eggs 12 pack','Dairy & Eggs','per 12','🥚',2.99),
('Gouda Cheese','Dairy & Eggs','per 400g','🧀',2.89),
('Gouda Young','Dairy & Eggs','per 400g','🧀',2.69),
('Gouda Old','Dairy & Eggs','per 300g','🧀',3.49),
('Edam Cheese','Dairy & Eggs','per 400g','🧀',2.79),
('Emmental Cheese','Dairy & Eggs','per 300g','🧀',3.29),
('Cheddar Cheese','Dairy & Eggs','per 200g','🧀',2.49),
('Brie Cheese','Dairy & Eggs','per 200g','🧀',2.99),
('Camembert','Dairy & Eggs','per 250g','🧀',2.79),
('Mozzarella','Dairy & Eggs','per 125g','🧀',0.99),
('Fresh Mozzarella','Dairy & Eggs','per 125g','🧀',1.49),
('Parmesan Block','Dairy & Eggs','per 200g','🧀',3.99),
('Grated Parmesan','Dairy & Eggs','per 80g','🧀',1.99),
('Cream Cheese','Dairy & Eggs','per 200g','🧀',1.29),
('Cottage Cheese','Dairy & Eggs','per 200g','🧀',1.49),
('Feta Cheese','Dairy & Eggs','per 200g','🧀',2.29),
('Blue Cheese','Dairy & Eggs','per 100g','🧀',2.49),
('Cheese Slices','Dairy & Eggs','per 200g','🧀',1.99),
('Butter Unsalted','Dairy & Eggs','per 250g','🧈',2.29),
('Butter Salted','Dairy & Eggs','per 250g','🧈',2.29),
('Margarine','Dairy & Eggs','per 500g','🧈',1.49),
('Cooking Butter','Dairy & Eggs','per 250g','🧈',1.99),
('Heavy Cream','Dairy & Eggs','per 200ml','🥛',1.09),
('Whipping Cream','Dairy & Eggs','per 250ml','🥛',1.29),
('Sour Cream','Dairy & Eggs','per 200ml','🥛',0.89),
('Creme Fraiche','Dairy & Eggs','per 200ml','🥛',1.19),
('Natural Yogurt','Dairy & Eggs','per 500g','🥛',0.99),
('Greek Yogurt','Dairy & Eggs','per 500g','🥛',1.79),
('Vanilla Yogurt','Dairy & Eggs','per 4 pack','🥛',1.49),
('Fruit Yogurt Strawberry','Dairy & Eggs','per 4 pack','🥛',1.59),
('Skyr Plain','Dairy & Eggs','per 450g','🥛',1.89),
('Drinking Yogurt','Dairy & Eggs','per 500ml','🥛',1.29),
('Chocolate Pudding','Dairy & Eggs','per 4 pack','🍫',1.79),
('Custard Vanilla','Dairy & Eggs','per 500ml','🍮',1.29),
('Rice Pudding','Dairy & Eggs','per 500g','🍚',1.49);

INSERT INTO temp_products VALUES
('Chicken Breast','Meat & Seafood','per kg','🍗',7.99),
('Chicken Thighs','Meat & Seafood','per kg','🍗',5.99),
('Chicken Drumsticks','Meat & Seafood','per kg','🍗',3.99),
('Chicken Wings','Meat & Seafood','per kg','🍗',4.49),
('Whole Chicken','Meat & Seafood','per kg','🍗',4.99),
('Chicken Mince','Meat & Seafood','per 500g','🍗',3.99),
('Turkey Breast','Meat & Seafood','per kg','🦃',9.49),
('Turkey Mince','Meat & Seafood','per 500g','🦃',3.99),
('Ground Beef','Meat & Seafood','per 500g','🥩',3.99),
('Beef Steak Sirloin','Meat & Seafood','per kg','🥩',19.99),
('Beef Steak Ribeye','Meat & Seafood','per kg','🥩',22.99),
('Beef Stewing Pieces','Meat & Seafood','per 500g','🥩',5.99),
('Beef Roast','Meat & Seafood','per kg','🥩',12.99),
('Pork Chops','Meat & Seafood','per kg','🥩',6.99),
('Pork Tenderloin','Meat & Seafood','per kg','🥩',9.99),
('Pork Mince','Meat & Seafood','per 500g','🥩',3.49),
('Pork Sausages','Meat & Seafood','per 6 pack','🌭',2.99),
('Bacon Smoked','Meat & Seafood','per 200g','🥓',2.49),
('Bacon Unsmoked','Meat & Seafood','per 200g','🥓',2.49),
('Pancetta','Meat & Seafood','per 100g','🥓',1.99),
('Ham Sliced','Meat & Seafood','per 150g','🍖',1.99),
('Salami','Meat & Seafood','per 100g','🍖',1.79),
('Chorizo','Meat & Seafood','per 200g','🍖',2.49),
('Prosciutto','Meat & Seafood','per 80g','🍖',2.99),
('Lamb Leg','Meat & Seafood','per kg','🍖',14.99),
('Lamb Chops','Meat & Seafood','per kg','🍖',16.99),
('Lamb Mince','Meat & Seafood','per 500g','🍖',5.49),
('Salmon Fillet Fresh','Meat & Seafood','per kg','🐟',14.99),
('Salmon Smoked','Meat & Seafood','per 100g','🐟',3.49),
('Cod Fillet','Meat & Seafood','per kg','🐟',12.99),
('Tuna Steak','Meat & Seafood','per kg','🐟',16.99),
('Shrimp Raw','Meat & Seafood','per 400g','🦐',6.99),
('Shrimp Cooked','Meat & Seafood','per 200g','🦐',4.49),
('Mussels Fresh','Meat & Seafood','per kg','🦪',3.99),
('Fish Fingers','Meat & Seafood','per 10 pack','🐟',2.49),
('Smoked Mackerel','Meat & Seafood','per 200g','🐟',2.99),
('Herring Fillets','Meat & Seafood','per 200g','🐟',2.49),
('Crab Sticks','Meat & Seafood','per 200g','🦀',1.99),
('White Bread','Bakery','per loaf','🍞',1.09),
('Whole Wheat Bread','Bakery','per loaf','🍞',1.29),
('Multigrain Bread','Bakery','per loaf','🍞',1.49),
('Sourdough Bread','Bakery','per loaf','🍞',2.49),
('Rye Bread','Bakery','per loaf','🍞',1.79),
('Baguette','Bakery','each','🥖',0.99),
('Ciabatta','Bakery','each','🥖',1.49),
('Focaccia','Bakery','each','🥖',1.99),
('Pita Bread 6 pack','Bakery','per 6','🥖',1.19),
('Tortilla Wraps 8 pack','Bakery','per 8','🌮',1.49),
('Naan Bread 2 pack','Bakery','per 2','🥖',1.29),
('Hamburger Buns 4 pack','Bakery','per 4','🍔',1.29),
('Hot Dog Buns 6 pack','Bakery','per 6','🌭',1.09),
('Croissants 4 pack','Bakery','per 4','🥐',1.99),
('Pain au Chocolat 4 pack','Bakery','per 4','🥐',2.29),
('Muffins Chocolate 4 pack','Bakery','per 4','🧁',2.49),
('Muffins Blueberry 4 pack','Bakery','per 4','🧁',2.49),
('Donuts 4 pack','Bakery','per 4','🍩',2.29),
('Cinnamon Rolls 4 pack','Bakery','per 4','🍥',2.99),
('Pancakes 6 pack','Bakery','per 6','🥞',1.79),
('Waffles Belgian 4 pack','Bakery','per 4','🧇',2.49),
('Crispbread','Bakery','per 250g','🍞',1.49),
('Breadsticks','Bakery','per 125g','🥖',0.99),
('Brioche Bread','Bakery','per loaf','🍞',2.29),
('Corn Tortillas 12 pack','Bakery','per 12','🌮',1.79),
('Pizza Dough','Bakery','per 400g','🍕',1.49),
('Crackers Water','Bakery','per 200g','🍪',1.29),
('Rice Cakes','Bakery','per 130g','🍘',1.19),
('Bagels 4 pack','Bakery','per 4','🥯',1.79);

INSERT INTO temp_products VALUES
('Spaghetti Pasta','Pantry','per 500g','🍝',0.79),
('Penne Pasta','Pantry','per 500g','🍝',0.79),
('Fusilli Pasta','Pantry','per 500g','🍝',0.79),
('Tagliatelle','Pantry','per 500g','🍝',0.99),
('Lasagna Sheets','Pantry','per 500g','🍝',1.19),
('Egg Noodles','Pantry','per 250g','🍜',0.99),
('Rice Noodles','Pantry','per 250g','🍜',1.29),
('Basmati Rice','Pantry','per kg','🍚',1.99),
('Jasmine Rice','Pantry','per kg','🍚',2.29),
('Long Grain Rice','Pantry','per kg','🍚',1.49),
('Brown Rice','Pantry','per kg','🍚',1.79),
('Risotto Rice','Pantry','per 500g','🍚',1.99),
('Couscous','Pantry','per 500g','🍚',1.29),
('Quinoa','Pantry','per 400g','🍚',2.99),
('Bulgur Wheat','Pantry','per 500g','🍚',1.49),
('Oats Rolled','Pantry','per kg','🥣',1.29),
('Oats Instant','Pantry','per 500g','🥣',1.49),
('Muesli','Pantry','per 750g','🥣',2.49),
('Granola','Pantry','per 500g','🥣',2.99),
('Cornflakes','Pantry','per 500g','🥣',1.79),
('Chocos Cereal','Pantry','per 500g','🥣',2.49),
('Flour All Purpose','Pantry','per kg','🌾',0.79),
('Flour Self Rising','Pantry','per kg','🌾',0.89),
('Flour Whole Wheat','Pantry','per kg','🌾',0.99),
('Sugar White','Pantry','per kg','🍬',0.89),
('Sugar Brown','Pantry','per 500g','🍬',0.99),
('Powdered Sugar','Pantry','per 500g','🍬',0.89),
('Honey','Pantry','per 350g','🍯',2.99),
('Maple Syrup','Pantry','per 250ml','🍯',4.49),
('Olive Oil Extra Virgin','Pantry','per 500ml','🫒',3.99),
('Olive Oil','Pantry','per 1L','🫒',4.99),
('Sunflower Oil','Pantry','per 1L','🫒',1.99),
('Coconut Oil','Pantry','per 500ml','🫒',3.49),
('Vegetable Oil','Pantry','per 1L','🫒',1.79),
('Balsamic Vinegar','Pantry','per 250ml','🫒',1.99),
('White Wine Vinegar','Pantry','per 500ml','🫒',1.49),
('Apple Cider Vinegar','Pantry','per 500ml','🫒',1.79),
('Soy Sauce','Pantry','per 250ml','🥫',1.49),
('Tomato Ketchup','Pantry','per 500ml','🥫',1.29),
('Mayonnaise','Pantry','per 500ml','🥫',1.79),
('Mustard Dijon','Pantry','per 200g','🥫',1.29),
('Mustard Whole Grain','Pantry','per 200g','🥫',1.49),
('BBQ Sauce','Pantry','per 500ml','🥫',1.99),
('Hot Sauce','Pantry','per 150ml','🌶️',1.79),
('Tomato Passata','Pantry','per 500ml','🥫',0.89),
('Chopped Tomatoes Can','Pantry','per 400g','🥫',0.69),
('Tomato Paste','Pantry','per 140g','🥫',0.59),
('Coconut Milk Can','Pantry','per 400ml','🥫',1.29),
('Chickpeas Can','Pantry','per 400g','🥫',0.79),
('Kidney Beans Can','Pantry','per 400g','🥫',0.79),
('Black Beans Can','Pantry','per 400g','🥫',0.89),
('Baked Beans','Pantry','per 400g','🥫',0.79),
('Lentils Red Dried','Pantry','per 500g','🥫',1.49),
('Lentils Green Dried','Pantry','per 500g','🥫',1.49),
('Sweet Corn Can','Pantry','per 340g','🌽',0.89),
('Tuna Can','Pantry','per 160g','🐟',1.29),
('Sardines Can','Pantry','per 120g','🐟',0.99),
('Peanut Butter','Pantry','per 350g','🥜',2.29),
('Almond Butter','Pantry','per 250g','🥜',3.99),
('Nutella','Pantry','per 400g','🍫',2.99),
('Jam Strawberry','Pantry','per 450g','🍓',1.49),
('Jam Apricot','Pantry','per 450g','🍑',1.49),
('Marmalade Orange','Pantry','per 450g','🍊',1.69),
('Chocolate Spread','Pantry','per 400g','🍫',2.49),
('Speculoos Spread','Pantry','per 400g','🍪',2.79),
('Salt Table','Pantry','per kg','🧂',0.49),
('Salt Sea','Pantry','per 500g','🧂',0.99),
('Black Pepper Ground','Pantry','per 50g','🧂',1.49),
('Paprika Spice','Pantry','per 50g','🧂',1.29),
('Cumin Ground','Pantry','per 40g','🧂',1.29),
('Cinnamon Ground','Pantry','per 40g','🧂',1.19),
('Mixed Herbs','Pantry','per 20g','🌿',0.99),
('Chicken Stock Cubes','Pantry','per 10 pack','🧂',0.99),
('Vegetable Stock Cubes','Pantry','per 10 pack','🧂',0.99),
('Beef Stock Cubes','Pantry','per 10 pack','🧂',0.99),
('Vanilla Extract','Pantry','per 38ml','🧂',2.49),
('Baking Powder','Pantry','per 100g','🧂',0.79),
('Baking Soda','Pantry','per 200g','🧂',0.69),
('Yeast Dried','Pantry','per 5 sachets','🧂',0.99),
('Cocoa Powder','Pantry','per 250g','🍫',1.99),
('Chocolate Chips','Pantry','per 200g','🍫',1.79),
('Cornstarch','Pantry','per 250g','🌾',0.89),
('Breadcrumbs','Pantry','per 400g','🍞',0.99),
('Panko Breadcrumbs','Pantry','per 200g','🍞',1.49),
('Gelatin Sheets','Pantry','per 10 pack','🧂',1.29),
('Frozen Pizza Margherita','Pantry','each','🍕',2.49),
('Frozen Pizza Pepperoni','Pantry','each','🍕',2.99),
('Frozen French Fries','Pantry','per kg','🍟',1.49),
('Frozen Peas','Pantry','per 900g','🫛',1.29),
('Frozen Spinach','Pantry','per 450g','🥬',0.99),
('Frozen Mixed Vegetables','Pantry','per 900g','🥦',1.49),
('Frozen Broccoli Florets','Pantry','per 600g','🥦',1.29),
('Frozen Corn','Pantry','per 900g','🌽',1.39),
('Frozen Berries Mix','Pantry','per 500g','🫐',2.99),
('Frozen Strawberries','Pantry','per 500g','🍓',2.49),
('Ice Cream Vanilla 1L','Pantry','per 1L','🍦',2.99),
('Ice Cream Chocolate 1L','Pantry','per 1L','🍦',2.99),
('Ice Cream Strawberry 1L','Pantry','per 1L','🍦',2.99),
('Ice Cream Bars 4-pack','Pantry','per 4','🍦',2.99),
('Frozen Chicken Nuggets','Pantry','per 500g','🍗',2.79),
('Frozen Fish Sticks 15','Pantry','per 15','🐟',2.99),
('Frozen Shrimp 400g','Pantry','per 400g','🦐',5.99),
('Frozen Waffles 10','Pantry','per 10','🧇',1.99),
('Frozen Croissants 6','Pantry','per 6','🥐',2.29),
('Dish Soap','Pantry','per 500ml','🧴',1.29),
('Laundry Detergent','Pantry','per 1L','🧴',3.99),
('Fabric Softener','Pantry','per 1L','🧴',2.49),
('All Purpose Cleaner','Pantry','per 750ml','🧴',1.99),
('Toilet Paper 8 rolls','Pantry','per 8','🧻',2.99),
('Kitchen Paper 2 rolls','Pantry','per 2','🧻',1.49),
('Bin Bags 20L','Pantry','per 40','🗑️',1.99),
('Cling Film','Pantry','per 30m','🫙',0.99),
('Aluminium Foil','Pantry','per 10m','🫙',1.29),
('Baking Paper','Pantry','per 10m','🫙',1.19),
('Sponges 3-pack','Pantry','per 3','🧽',0.99),
('Hand Soap','Pantry','per 300ml','🧴',1.29),
('Toothpaste','Pantry','per 75ml','🪥',1.49),
('Shampoo','Pantry','per 250ml','🧴',2.49),
('Shower Gel','Pantry','per 250ml','🧴',1.99),
('Deodorant Spray','Pantry','per 150ml','🧴',2.29);

INSERT INTO temp_products VALUES
('Coca-Cola 6-pack','Beverages','6 x 330ml','🥤',3.49),
('Coca-Cola 1.5L','Beverages','per 1.5L','🥤',1.49),
('Coca-Cola Zero 6-pack','Beverages','6 x 330ml','🥤',3.49),
('Fanta Orange 6-pack','Beverages','6 x 330ml','🥤',3.29),
('Sprite 6-pack','Beverages','6 x 330ml','🥤',3.29),
('Pepsi 6-pack','Beverages','6 x 330ml','🥤',3.29),
('7Up 6-pack','Beverages','6 x 330ml','🥤',3.09),
('Sparkling Water 1.5L','Beverages','per 1.5L','💧',0.49),
('Still Water 6-pack','Beverages','6 x 1.5L','💧',1.99),
('Mineral Water 6-pack','Beverages','6 x 500ml','💧',1.79),
('Orange Juice Fresh','Beverages','per 1L','🧃',2.49),
('Orange Juice Carton','Beverages','per 1L','🧃',1.49),
('Apple Juice','Beverages','per 1L','🧃',1.29),
('Multivitamin Juice','Beverages','per 1L','🧃',1.69),
('Cranberry Juice','Beverages','per 1L','🧃',1.99),
('Tomato Juice','Beverages','per 1L','🧃',1.29),
('Lemonade','Beverages','per 1.5L','🍋',0.99),
('Ice Tea Peach','Beverages','per 1.5L','🧃',1.29),
('Ice Tea Lemon','Beverages','per 1.5L','🧃',1.29),
('Energy Drink','Beverages','per 250ml','⚡',0.99),
('Energy Drink 4-pack','Beverages','4 x 250ml','⚡',3.49),
('Red Bull 4-pack','Beverages','4 x 250ml','⚡',5.99),
('Coffee Beans 500g','Beverages','per 500g','☕',4.99),
('Coffee Ground 250g','Beverages','per 250g','☕',2.99),
('Instant Coffee 200g','Beverages','per 200g','☕',3.49),
('Coffee Pods Lungo 10','Beverages','per 10','☕',2.99),
('Coffee Pods Espresso 10','Beverages','per 10','☕',2.99),
('Decaf Coffee 250g','Beverages','per 250g','☕',3.29),
('Black Tea 20 bags','Beverages','per 20','🫖',1.29),
('Green Tea 20 bags','Beverages','per 20','🍵',1.49),
('Chamomile Tea 20 bags','Beverages','per 20','🍵',1.49),
('Mint Tea 20 bags','Beverages','per 20','🍵',1.49),
('Earl Grey Tea 20 bags','Beverages','per 20','🫖',1.69),
('Hot Chocolate Powder','Beverages','per 400g','🍫',2.49),
('Beer Lager 6-pack','Beverages','6 x 330ml','🍺',4.49),
('Beer Wheat 6-pack','Beverages','6 x 330ml','🍺',5.49),
('Beer Tripel','Beverages','per 330ml','🍺',1.99),
('Wine Red Table','Beverages','per 750ml','🍷',3.99),
('Wine White Table','Beverages','per 750ml','🍷',3.99),
('Wine Rose','Beverages','per 750ml','🍷',4.49),
('Prosecco','Beverages','per 750ml','🥂',6.99),
('Potato Chips Classic','Snacks','per 200g','🥔',1.29),
('Potato Chips Paprika','Snacks','per 200g','🥔',1.29),
('Potato Chips Salt Vinegar','Snacks','per 200g','🥔',1.29),
('Tortilla Chips','Snacks','per 200g','🌮',1.49),
('Nachos Cheese','Snacks','per 200g','🌮',1.69),
('Peanuts Salted','Snacks','per 300g','🥜',1.79),
('Peanuts Honey Roasted','Snacks','per 200g','🥜',1.99),
('Mixed Nuts','Snacks','per 200g','🥜',2.99),
('Cashew Nuts','Snacks','per 200g','🥜',3.49),
('Almonds','Snacks','per 200g','🥜',2.99),
('Trail Mix','Snacks','per 200g','🥜',2.49),
('Popcorn Microwave 3-pack','Snacks','per 3 pack','🍿',1.79),
('Popcorn Sweet','Snacks','per 100g','🍿',1.29),
('Pretzels','Snacks','per 200g','🥨',1.19),
('Cheese Crackers','Snacks','per 150g','🧀',1.49),
('Rice Crackers','Snacks','per 100g','🍘',1.29),
('Dark Chocolate Bar','Snacks','per 100g','🍫',1.49),
('Milk Chocolate Bar','Snacks','per 100g','🍫',1.29),
('White Chocolate Bar','Snacks','per 100g','🍫',1.29),
('Chocolate Hazelnut Bar','Snacks','per 100g','🍫',1.69),
('Chocolate Truffles','Snacks','per 200g','🍫',3.49),
('Chocolate Box Assorted','Snacks','per 250g','🍫',4.99),
('Cookies Chocolate Chip','Snacks','per 200g','🍪',1.49),
('Cookies Double Choc','Snacks','per 200g','🍪',1.69),
('Cookies Oatmeal Raisin','Snacks','per 200g','🍪',1.49),
('Speculoos Cookies','Snacks','per 250g','🍪',1.79),
('Stroopwafels','Snacks','per 8 pack','🧇',1.99),
('Wafer Bars','Snacks','per 5 pack','🍫',1.19),
('Candy Gummies Bears','Snacks','per 200g','🍬',0.99),
('Candy Gummies Worms','Snacks','per 200g','🍬',0.99),
('Licorice','Snacks','per 200g','🍬',1.29),
('Marshmallows','Snacks','per 200g','🍬',1.19),
('Lollipops 10-pack','Snacks','per 10','🍭',1.49),
('Mints','Snacks','per 50g','🍬',0.79),
('Chewing Gum 10-pack','Snacks','per 10','🍬',1.29),
('Protein Bar','Snacks','each','💪',1.79),
('Muesli Bar 6-pack','Snacks','per 6','🥣',1.99),
('Fruit Snack Bars 5-pack','Snacks','per 5','🍎',1.79),
('Dried Mango','Snacks','per 100g','🥭',1.99),
('Dried Banana Chips','Snacks','per 150g','🍌',1.49),
('Olives Green','Snacks','per 200g','🫒',1.79),
('Olives Black','Snacks','per 200g','🫒',1.79),
('Hummus Classic','Snacks','per 200g','🫘',1.49),
('Guacamole','Snacks','per 200g','🥑',2.29),
('Salsa Dip','Snacks','per 300g','🫙',1.99);

-- Now generate products and prices
DO $$
DECLARE
  r RECORD;
  new_id uuid;
  store_ids text[] := ARRAY['aldi','albert_heijn','carrefour','colruyt','jumbo','lidl'];
  multipliers numeric[] := ARRAY[1.0, 1.25, 1.15, 1.10, 1.20, 0.95];
  store_price numeric;
  sale_chance integer;
BEGIN
  FOR r IN SELECT * FROM temp_products LOOP
    SELECT id INTO new_id FROM public.products WHERE name = r.name LIMIT 1;
    
    IF new_id IS NULL THEN
      INSERT INTO public.products (name, category, unit, image)
      VALUES (r.name, r.category, r.unit, r.image)
      RETURNING id INTO new_id;
    END IF;

    FOR i IN 1..6 LOOP
      store_price := ROUND((r.base_price * multipliers[i] * (0.92 + random() * 0.16))::numeric, 2);
      sale_chance := floor(random() * 10)::integer;
      
      -- Skip if price already exists for this product+store
      IF NOT EXISTS (SELECT 1 FROM public.product_prices WHERE product_id = new_id AND store_id = store_ids[i]) THEN
        INSERT INTO public.product_prices (product_id, store_id, price, on_sale, scraped_at)
        VALUES (new_id, store_ids[i], store_price, sale_chance = 0, now());
      END IF;
    END LOOP;
  END LOOP;
END $$;

DROP TABLE IF EXISTS temp_products;
